modify the -t and failed login

diff --git a/utilities/openemr-env-migrator/openemr-env-migrator b/utilities/openemr-env-migrator/openemr-env-migrator
--- a/utilities/openemr-env-migrator/openemr-env-migrator
+++ b/utilities/openemr-env-migrator/openemr-env-migrator
@@ -1,5 +1,6 @@
 #!/bin/bash
 # Function: migrate the container environment
+first_arg=$1
 
 # Create the storage location if not exist
 # For the local env
@@ -124,20 +125,33 @@ commit_and_save_container(){
 }
 
 # Script Usage
-if [ $# -lt 1 ]
-then
+script_usage() {
+	echo "Usage:"
+	echo "    -t,      Specify the migration type e.g. local, remote, set, single."
+	echo "    -s,      Specify the migration container source directory." 
+	echo "    -d,      Specify the migration container target directory." 
+	echo "    -u,      Specify the target host ssh user." 
+	echo "    -h,      Specify the target host ip." 
+	echo "    -m,      Specify the migration source container." 
+	echo "    -n,      Specify the migration new container name." 
+	echo ''
 	echo -e "\033[0m\033[36mMigrate all the containers: \033[0m"
-	echo -e " \033[0m\033[33m Scenario one: Please provide the <source dir> and <target dir> if migrate in local.\033[0m"
+	echo -e " \033[0m\033[33m Scenario one: Migrate in local.\033[0m"
 	echo "   e.g. `basename $0` -t local -s /var/lib/docker/ -d /data/docker/"
-	echo -e " \033[0m\033[33m Scenario two: Please provide the <source dir>, <target ssh user>, <target ip> and <target dir> if migrate to remote host.\033[0m"
+	echo -e " \033[0m\033[33m Scenario two: Migrate to remote host.\033[0m"
 	echo -e "   \033[0m\033[32mFirst step in local:\033[0m    `basename $0` -t remote -s /var/lib/docker/ -u testuser -h 192.168.117.117 -d /data/docker/"
 	echo -e "   \033[0m\033[32mSecond step in remote:\033[0m  `basename $0` -t set -d /data/docker/"
 	echo -e "\033[0m\033[35m  **NOTE-1**: Do not forget the last slash of source dir, e.g. /var/lib/docker/ \033[0m"
 	echo -e "\033[0m\033[35m  **NOTE-2**: Please make sure there is the same source code dir in the remote host for easy or insane env and setup the base container services. \033[0m"
+	echo ''
 	echo -e "\033[0m\033[36mMigrate the single container: \033[0m"
-	echo -e  " \033[0m\033[33m Please provide the <migrate container name>, <new container name>, <target ssh user> and <target ip>.\033[0m"
 	echo "   e.g. `basename $0` -t single -m  brave_snyder -n http -u testuser -h 192.168.117.117"
 	exit
+}
+
+if [ "$first_arg" != "-t" ]
+then
+	script_usage
 fi
 
 # Define the options
@@ -172,6 +186,11 @@ do
 		# The migrate type, e.g. local, remote, set, single
 		migrate_type=$OPTARG
 		;;
+		\?)
+		echo "Invalid option: -$opt" >&2
+		script_usage
+		exit
+		;;
     esac
 done
 
@@ -196,6 +215,11 @@ then
 	set_daemon_json_file $migrate_target_dir
 	start_all_containers
 # Migrate the single container
-else
+elif [ "$migrate_type" == 'single' ]
+then
 	commit_and_save_container $migrate_container_name $container_name $target_ssh_user $target_ip
+else
+	echo -e "\033[0m\033[31mInvalid migrate type, e.g. local, remote, set, single. \033[0m"
+	script_usage
+	exit
 fi
